version: 1

formatters:
  simple:
    format: '%(asctime)s - %(levelname)-8s - %(message)s'
    datefmt: "%d/%m/%Y %H:%M:%S"

handlers:
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: simple
    filename: ./logs/my_application.log
    when: midnight
    backupCount: 7
    encoding: utf8

  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stderr   # important !

loggers:
  simpleLogger:
    handlers: [file]
    level: INFO
    propagate: no

root:
  level: INFO
  handlers: [file]
